### ISSUE TITLE
Sideberry navigation-sidebar not opening

### ISSUE THREAD

**Issue by simon-ami** [scientiac/scifox#3]
Hi scientiac,

thanks a lot for this very sleek theme!

Unfortunatly, i'm currently having an issue with the sidebar (configured with sideberry, using your suggested settings) not opening. So sideberry is active, but when hover the mouse over the tab column on the left, it doesn't expand to the right anymore (after a Firefox restart, not sure if an update was installed).

I'm on Windows, and currently using the lates stable Firefox version 133.0 (64-bit).

What might be helpful context: I was previously (~ a month ago) signed up for the beta version of the stable release, in which I encountered this same issue, because of which i "downgraded" to the stable release. So this might indeed be subject to an update which may just have been rolled out.

**Comment by scientiac** [comment]
I have pushed an update, can you please try and give me a response if it works.

**Comment by simon-ami** [comment]
It's working again, thanks for the quick update.

Have a nice day!

**Comment by simon-ami** [comment]
Hi again (sadly under not-so-well circumstances lol)!

I'm having the same issue again after an update to v140.0. I have sadly not been able to fix it myself, but would be very happy to continue using this nice theme. If you have the time and energy, you can be sure of my gratitude!

Let me know if I can provide you with more context to help diagnose the issue.

**Comment by simon-ami** [comment]
A temporary workaround for me is to change lines 36-38 (in the sideberry config section) from

```css
#sidebar-box[...]:hover > #sidebar {
  min-width: var(--uc-sidebar-hover-width) !important;
  transition-delay: 0ms !important
}
```

to

```css
#sidebar-box[...]:hover {
  min-width: var(--uc-sidebar-hover-width) !important;
  max-width: var(--uc-sidebar-hover-width) !important;
}
```
